# Site settings
title: scott on quine
email: scott@quine.io
description: > # this means to ignore newlines until "baseurl:"
    A journal of my sparse successes and frequent abominations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scott.quine.io" # the base hostname & protocol for your site
github_username:  phonyphonecall

# Build settings
markdown: kramdown
